language: node_js
node_js:
  - node
  - "lts/*"
services:
  - postgresql
  - redis-server
  
before_script:
  - npm install
  - psql -c 'CREATE DATABASE TicketerRewrite;' -U postgres
  - psql -c 'CREATE TABLE IF NOT EXISTS servers(serverid varchar PRIMARY KEY, currentticket smallint DEFAULT 1, setup boolean DEFAULT FALSE, userid varchar);' -U postgres
  - psql -c 'CREATE TABLE IF NOT EXISTS premium(userid varchar, serverid varchar, key varchar, enabled boolean DEFAULT FALSE, paymentid varchar DEFAULT 0);' -U postgres
  - psql -c 'CREATE TABLE IF NOT EXISTS blacklist(userid varchar, serverid varchar);' -U postgres
  - psql -c 'CREATE TABLE IF NOT EXISTS payments(userid varchar, paymentid varchar);' -U postgres
  - psql -c 'CREATE TABLE IF NOT EXISTS votes(userid varchar PRIMARY KEY, count smallint);' -U postgres

script:
  - npm run test
  - npm run test-coverage

after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL